cache:
  directories:
    - $HOME/.composer/cache/files

language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

install:
  - composer install --prefer-dist

before_script:
  - for P in src tests; do find $P -type f -name '*.php' -exec php -l {} \;; done

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
